DROP TABLE IF EXISTS cards;
DROP TABLE IF EXISTS transactions;
DROP TABLE IF EXISTS wallets;
DROP TABLE IF EXISTS idempotency_keys;
DROP TABLE IF EXISTS users;
DROP SEQUENCE IF EXISTS wallet_number_seq;
